package com.nhatkytimestiming.app;
import android.app.*;import android.appwidget.*;import android.content.*;import android.net.Uri;import android.view.View;import android.widget.RemoteViews;import org.json.*;import java.text.SimpleDateFormat;import java.util.*;
public class ActivityWidgetProvider extends AppWidgetProvider{
 private static final Object STATE_LOCK=new Object();
 public static final String DATA_PREFS="daily_time_state",STATE_KEY="state",CONFIG_PREFS="activity_widget_config",ACTION="com.nhatkytimestiming.app.WIDGET_ACTION",TICK="com.nhatkytimestiming.app.TIMER_TICK";
 public void onUpdate(Context c,AppWidgetManager m,int[] ids){for(int id:ids)update(c,m,id);} public void onEnabled(Context c){refreshAll(c);} public void onDeleted(Context c,int[] ids){SharedPreferences.Editor e=c.getSharedPreferences(CONFIG_PREFS,0).edit();for(int id:ids)e.remove("selected_"+id);e.commit();} public void onReceive(Context c,Intent i){super.onReceive(c,i);String a=i==null?"":i.getAction();if(ACTION.equals(a)){perform(c,i.getStringExtra("activity_id"));return;}if(TICK.equals(a)){refreshAll(c);schedule(c);return;}if(Intent.ACTION_BOOT_COMPLETED.equals(a)||Intent.ACTION_MY_PACKAGE_REPLACED.equals(a)||Intent.ACTION_TIME_CHANGED.equals(a)||Intent.ACTION_TIMEZONE_CHANGED.equals(a)||Intent.ACTION_DATE_CHANGED.equals(a)){refreshAll(c);schedule(c);}}
 static JSONObject state(Context c){synchronized(STATE_LOCK){return readStateUnlocked(c);}} static JSONObject readStateUnlocked(Context c){try{return new JSONObject(c.getSharedPreferences(DATA_PREFS,0).getString(STATE_KEY,"{}"));}catch(Exception e){return new JSONObject();}}
 public static boolean commitStateIfNewer(Context c,String json){synchronized(STATE_LOCK){try{JSONObject incoming=new JSONObject(json==null?"{}":json),current=readStateUnlocked(c);long inRev=incoming.optLong("revision",0L),curRev=current.optLong("revision",0L);if(inRev<curRev)return false;if(inRev<=curRev)incoming.put("revision",curRev+1L);boolean ok=c.getSharedPreferences(DATA_PREFS,0).edit().putString(STATE_KEY,incoming.toString()).commit();if(ok)refreshAll(c);return ok;}catch(Exception e){return false;}}}
 static JSONArray types(JSONObject s){JSONArray a=s.optJSONArray("types");return a==null?new JSONArray():a;} static JSONObject find(JSONArray a,String id){for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&id.equals(o.optString("id")))return o;}return null;}
 static String iso(Date d){SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",Locale.US);f.setTimeZone(TimeZone.getTimeZone("UTC"));return f.format(d);} static long parsed(String x){if(x==null||x.isEmpty())return System.currentTimeMillis();for(String p:new String[]{"yyyy-MM-dd'T'HH:mm:ss.SSSX","yyyy-MM-dd'T'HH:mm:ssX","yyyy-MM-dd'T'HH:mm:ss.SSSXXX","yyyy-MM-dd'T'HH:mm:ssXXX"})try{return new SimpleDateFormat(p,Locale.US).parse(x).getTime();}catch(Exception ignored){}for(String p:new String[]{"yyyy-MM-dd'T'HH:mm:ss.SSS","yyyy-MM-dd'T'HH:mm:ss","yyyy-MM-dd'T'HH:mm"})try{SimpleDateFormat f=new SimpleDateFormat(p,Locale.US);f.setTimeZone(TimeZone.getDefault());return f.parse(x).getTime();}catch(Exception ignored){}return System.currentTimeMillis();} static String elapsed(long ms){long t=Math.max(0,ms)/1000,h=t/3600,m=t%3600/60,s=t%60;return h>0?String.format(Locale.US,"%d:%02d:%02d",h,m,s):String.format(Locale.US,"%02d:%02d",m,s);}
 static void perform(Context c,String id){synchronized(STATE_LOCK){try{JSONObject s=readStateUnlocked(c),active=s.optJSONObject("active");if(active==null)active=new JSONObject();JSONArray logs=s.optJSONArray("logs");if(logs==null)logs=new JSONArray();JSONObject t=find(types(s),id);if(t==null)return;Date now=new Date();if("timing".equals(t.optString("mode"))){if(active.has(id)){String st=active.optString(id);JSONObject l=new JSONObject();l.put("id","widget_"+Math.max(System.currentTimeMillis(),s.optLong("revision",0L)+1L));l.put("typeId",id);l.put("mode","timing");l.put("timestamp",st);l.put("startTime",st);l.put("endTime",iso(now));l.put("durationMs",Math.max(0,now.getTime()-parsed(st)));logs.put(l);active.remove(id);}else active.put(id,iso(now));}else{JSONObject l=new JSONObject();l.put("id","widget_"+Math.max(System.currentTimeMillis(),s.optLong("revision",0L)+1L));l.put("typeId",id);l.put("mode","times");l.put("timestamp",iso(now));l.put("durationMs",0);logs.put(l);}s.put("logs",logs);s.put("active",active);long previous=s.optLong("revision",0L);s.put("revision",Math.max(System.currentTimeMillis(),previous+1L));boolean saved=c.getSharedPreferences(DATA_PREFS,0).edit().putString(STATE_KEY,s.toString()).commit();if(saved){refreshAll(c);schedule(c);}}catch(Exception ignored){}}}
 static PendingIntent action(Context c,int wid,int slot,String id){Intent i=new Intent(c,ActivityWidgetProvider.class).setAction(ACTION).putExtra("activity_id",id);i.setData(Uri.parse("dailytime://act/"+wid+"/"+slot+"/"+Uri.encode(id)));return PendingIntent.getBroadcast(c,wid*100+slot,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);} static PendingIntent config(Context c,int wid,int slot){Intent i=new Intent(c,WidgetConfigActivity.class).putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,wid);i.setData(Uri.parse("dailytime://config/"+wid+"/"+slot));return PendingIntent.getActivity(c,wid*100+slot,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 static void schedule(Context c){JSONObject a=state(c).optJSONObject("active");AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);PendingIntent p=PendingIntent.getBroadcast(c,9090,new Intent(c,ActivityWidgetProvider.class).setAction(TICK),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);am.cancel(p);if(a!=null&&a.length()>0)am.set(AlarmManager.RTC,System.currentTimeMillis()+15000,p);} public static void refreshAll(Context c){AppWidgetManager m=AppWidgetManager.getInstance(c);for(int id:m.getAppWidgetIds(new ComponentName(c,ActivityWidgetProvider.class)))update(c,m,id);}
 public static void update(Context c,AppWidgetManager m,int wid){try{RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.widget_activity_grid);JSONObject s=state(c),active=s.optJSONObject("active");if(active==null)active=new JSONObject();JSONArray all=types(s),sel;try{sel=new JSONArray(c.getSharedPreferences(CONFIG_PREFS,0).getString("selected_"+wid,"[]"));}catch(Exception e){sel=new JSONArray();}for(int i=1;i<=20;i++){int cell=id(c,"cell"+i),icon=id(c,"icon"+i),name=id(c,"name"+i),run=id(c,"run"+i);JSONObject o=i<=sel.length()?find(all,sel.optString(i-1)):null;if(o==null||!o.optBoolean("enabled",true)){v.setTextViewText(icon,"+");v.setTextViewText(name,"");v.setTextViewText(run,"");v.setViewVisibility(run,View.GONE);v.setOnClickPendingIntent(cell,config(c,wid,i));}else{String aid=o.optString("id");v.setTextViewText(icon,o.optString("icon","•"));v.setTextViewText(name,o.optString("name",""));if("timing".equals(o.optString("mode"))&&active.has(aid)){v.setTextViewText(run,elapsed(System.currentTimeMillis()-parsed(active.optString(aid))));v.setViewVisibility(run,View.VISIBLE);}else{v.setTextViewText(run,"");v.setViewVisibility(run,View.GONE);}v.setOnClickPendingIntent(cell,action(c,wid,i,aid));}}m.updateAppWidget(wid,v);schedule(c);}catch(Exception error){RemoteViews fallback=new RemoteViews(c.getPackageName(),R.layout.widget_activity_grid);for(int i=1;i<=20;i++){int cell=id(c,"cell"+i),icon=id(c,"icon"+i),name=id(c,"name"+i),run=id(c,"run"+i);fallback.setTextViewText(icon,"+");fallback.setTextViewText(name,"");fallback.setTextViewText(run,"");fallback.setViewVisibility(run,View.GONE);fallback.setOnClickPendingIntent(cell,config(c,wid,i));}m.updateAppWidget(wid,fallback);}} static int id(Context c,String n){return c.getResources().getIdentifier(n,"id",c.getPackageName());}
}
