package com.nhatkytimestiming.app;
import android.app.*;import android.appwidget.*;import android.content.*;import android.net.Uri;import android.os.Bundle;import android.view.View;import android.widget.RemoteViews;import org.json.*;import java.text.SimpleDateFormat;import java.util.*;
public class ActivityWidgetProvider extends AppWidgetProvider{
 public static final String DATA_PREFS="daily_time_state",STATE_KEY="state",CONFIG_PREFS="activity_widget_config",ACTION="com.nhatkytimestiming.app.WIDGET_ACTION",TICK="com.nhatkytimestiming.app.TIMER_TICK";
 public void onUpdate(Context c,AppWidgetManager m,int[] ids){for(int id:ids)update(c,m,id);} public void onEnabled(Context c){refreshAll(c);} public void onAppWidgetOptionsChanged(Context c,AppWidgetManager m,int id,Bundle o){update(c,m,id);} public void onDeleted(Context c,int[] ids){SharedPreferences.Editor e=c.getSharedPreferences(CONFIG_PREFS,0).edit();for(int id:ids)e.remove("selected_"+id);e.commit();}
 public void onReceive(Context c,Intent i){super.onReceive(c,i);String a=i==null?"":i.getAction();if(ACTION.equals(a)){perform(c,i.getStringExtra("activity_id"));return;}if(TICK.equals(a)){refreshAll(c);scheduleTick(c);return;}if(Intent.ACTION_BOOT_COMPLETED.equals(a)||Intent.ACTION_MY_PACKAGE_REPLACED.equals(a)){refreshAll(c);scheduleTick(c);}}
 static JSONObject state(Context c){try{return new JSONObject(c.getSharedPreferences(DATA_PREFS,0).getString(STATE_KEY,"{}"));}catch(Exception e){return new JSONObject();}}
 static JSONArray types(JSONObject s){JSONArray a=s.optJSONArray("types");return a==null?new JSONArray():a;} static JSONObject find(JSONArray a,String id){for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&id.equals(o.optString("id")))return o;}return null;}
 static String iso(Date d){return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss",Locale.US).format(d);} static long parsed(String x){if(x==null)return System.currentTimeMillis();String[] p={"yyyy-MM-dd'T'HH:mm:ss.SSSXXX","yyyy-MM-dd'T'HH:mm:ssXXX","yyyy-MM-dd'T'HH:mm:ss.SSS","yyyy-MM-dd'T'HH:mm:ss","yyyy-MM-dd'T'HH:mm"};for(String q:p)try{return new SimpleDateFormat(q,Locale.US).parse(x).getTime();}catch(Exception ignored){}return System.currentTimeMillis();}
 static String elapsed(long ms){long t=Math.max(0,ms)/1000,h=t/3600,m=t%3600/60,s=t%60;return h>0?String.format(Locale.US,"%d:%02d:%02d",h,m,s):String.format(Locale.US,"%02d:%02d",m,s);}
 static void perform(Context c,String id){if(id==null)return;try{JSONObject s=state(c);JSONArray ts=types(s),logs=s.optJSONArray("logs");if(logs==null)logs=new JSONArray();JSONObject active=s.optJSONObject("active");if(active==null)active=new JSONObject();JSONObject t=find(ts,id);if(t==null)return;Date now=new Date();if("timing".equals(t.optString("mode"))){if(active.has(id)){String st=active.optString(id);JSONObject l=new JSONObject();l.put("id",System.currentTimeMillis());l.put("typeId",id);l.put("mode","timing");l.put("timestamp",st);l.put("startTime",st);l.put("endTime",iso(now));l.put("durationMs",Math.max(0,now.getTime()-parsed(st)));logs.put(l);active.remove(id);}else active.put(id,iso(now));}else{JSONObject l=new JSONObject();l.put("id",System.currentTimeMillis());l.put("typeId",id);l.put("mode","times");l.put("timestamp",iso(now));l.put("durationMs",0);logs.put(l);}s.put("logs",logs);s.put("active",active);s.put("revision",System.currentTimeMillis());c.getSharedPreferences(DATA_PREFS,0).edit().putString(STATE_KEY,s.toString()).commit();refreshAll(c);scheduleTick(c);}catch(Exception ignored){}}
 static PendingIntent action(Context c,int wid,int slot,String id){Intent i=new Intent(c,ActivityWidgetProvider.class);i.setAction(ACTION);i.putExtra("activity_id",id);i.setData(Uri.parse("dailytime://act/"+wid+"/"+slot+"/"+Uri.encode(id)));return PendingIntent.getBroadcast(c,wid*100+slot,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 static PendingIntent config(Context c,int wid,int slot){Intent i=new Intent(c,WidgetConfigActivity.class);i.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,wid);i.setData(Uri.parse("dailytime://config/"+wid+"/"+slot));return PendingIntent.getActivity(c,wid*100+slot,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 public static int capacity(Context c,int wid){Bundle o=AppWidgetManager.getInstance(c).getAppWidgetOptions(wid);return o.getInt(AppWidgetManager.OPTION_APPWIDGET_MIN_HEIGHT,110)>=180?20:10;}
 public static void refreshAll(Context c){AppWidgetManager m=AppWidgetManager.getInstance(c);for(int id:m.getAppWidgetIds(new ComponentName(c,ActivityWidgetProvider.class)))update(c,m,id);}
 static boolean anyRunning(JSONObject active){return active!=null&&active.length()>0;}
 static void scheduleTick(Context c){JSONObject a=state(c).optJSONObject("active");AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);Intent i=new Intent(c,ActivityWidgetProvider.class).setAction(TICK);PendingIntent p=PendingIntent.getBroadcast(c,9090,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);am.cancel(p);if(anyRunning(a))am.set(AlarmManager.RTC,System.currentTimeMillis()+15000,p);}
 public static void update(Context c,AppWidgetManager m,int wid){try{RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.widget_activity_grid);JSONObject s=state(c);JSONArray all=types(s);JSONObject active=s.optJSONObject("active");if(active==null)active=new JSONObject();JSONArray selected;try{selected=new JSONArray(c.getSharedPreferences(CONFIG_PREFS,0).getString("selected_"+wid,"[]"));}catch(Exception e){selected=new JSONArray();}int cap=capacity(c,wid);v.setViewVisibility(R.id.row3,cap==20?View.VISIBLE:View.GONE);v.setViewVisibility(R.id.row4,cap==20?View.VISIBLE:View.GONE);for(int i=1;i<=20;i++){int cell=id(c,"cell"+i),icon=id(c,"icon"+i),name=id(c,"name"+i),run=id(c,"run"+i);if(i>cap){v.setViewVisibility(cell,View.GONE);continue;}v.setViewVisibility(cell,View.VISIBLE);JSONObject o=i<=selected.length()?find(all,selected.optString(i-1)):null;if(o==null||!o.optBoolean("enabled",true)){v.setTextViewText(icon,"+");v.setTextViewText(name,"");v.setTextViewText(run,"");v.setViewVisibility(run,View.GONE);v.setOnClickPendingIntent(cell,config(c,wid,i));}else{String aid=o.optString("id");v.setTextViewText(icon,o.optString("icon","•"));v.setTextViewText(name,o.optString("name",""));if("timing".equals(o.optString("mode"))&&active.has(aid)){v.setTextViewText(run,elapsed(System.currentTimeMillis()-parsed(active.optString(aid))));v.setViewVisibility(run,View.VISIBLE);}else{v.setTextViewText(run,"");v.setViewVisibility(run,View.GONE);}v.setOnClickPendingIntent(cell,action(c,wid,i,aid));}}m.updateAppWidget(wid,v);scheduleTick(c);}catch(Exception e){}}
 static int id(Context c,String n){return c.getResources().getIdentifier(n,"id",c.getPackageName());}
}
