package com.nhatkytimestiming.app;
import android.content.*;import org.json.*;import java.text.SimpleDateFormat;import java.util.*;import java.util.concurrent.atomic.AtomicLong;
public final class NativeCommandProcessor{
 private static final Object LOCK=new Object();private static final AtomicLong SEQ=new AtomicLong();private static final int RECENT_LIMIT=100;private static final long TIMING_DEBOUNCE_MS=800L;
 public static final String APPLIED="APPLIED",DUPLICATE="DUPLICATE_IGNORED",MISMATCH="EXPECTED_STATE_MISMATCH",MODE_MISMATCH="MODE_MISMATCH",NOT_FOUND="ACTIVITY_NOT_FOUND",DISABLED="ACTIVITY_DISABLED",SESSION_MISMATCH="TIMING_SESSION_MISMATCH",INVALID="INVALID_COMMAND",FAILED="PERSIST_FAILED";
 private NativeCommandProcessor(){}
 static String utc(){SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",Locale.US);f.setTimeZone(TimeZone.getTimeZone("UTC"));return f.format(new Date());}
 static long parse(String x){if(x==null)return System.currentTimeMillis();for(String p:new String[]{"yyyy-MM-dd'T'HH:mm:ss.SSSX","yyyy-MM-dd'T'HH:mm:ssX","yyyy-MM-dd'T'HH:mm:ss.SSSXXX","yyyy-MM-dd'T'HH:mm:ssXXX","yyyy-MM-dd'T'HH:mm:ss.SSS","yyyy-MM-dd'T'HH:mm:ss"})try{return new SimpleDateFormat(p,Locale.US).parse(x).getTime();}catch(Exception ignored){}return System.currentTimeMillis();}
 static JSONObject state(Context c){try{return new JSONObject(c.getSharedPreferences(ActivityWidgetProvider.DATA_PREFS,0).getString(ActivityWidgetProvider.STATE_KEY,"{}"));}catch(Exception e){return new JSONObject();}}
 static JSONArray array(JSONObject s,String key){JSONArray a=s.optJSONArray(key);return a==null?new JSONArray():a;}static JSONObject object(JSONObject s,String key){JSONObject o=s.optJSONObject(key);return o==null?new JSONObject():o;}
 static JSONObject activity(JSONObject s,String id){JSONArray a=array(s,"types");for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&id.equals(o.optString("id")))return o;}return null;}
 static JSONObject result(String commandId,String actionId,String status,long revision,String reason){JSONObject r=new JSONObject();try{r.put("commandId",commandId);r.put("actionId",actionId);r.put("status",status);r.put("revision",revision);r.put("reason",reason==null?JSONObject.NULL:reason);r.put("shouldRefresh",true);}catch(Exception ignored){}return r;}
 static JSONObject recent(JSONObject s,String actionId){JSONArray a=array(s,"recentActions");for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&actionId.equals(o.optString("actionId")))return o;}return null;}
 static void remember(JSONObject s,String actionId,String type,String status,long revision)throws JSONException{JSONArray a=array(s,"recentActions");JSONObject receipt=new JSONObject();receipt.put("actionId",actionId);receipt.put("commandType",type);receipt.put("status",status);receipt.put("processedRevision",revision);receipt.put("processedAt",utc());a.put(receipt);while(a.length()>RECENT_LIMIT)a.remove(0);s.put("recentActions",a);}
 static boolean commit(Context c,JSONObject s){return c.getSharedPreferences(ActivityWidgetProvider.DATA_PREFS,0).edit().putString(ActivityWidgetProvider.STATE_KEY,s.toString()).commit();}
 public static String nextActionId(int wid,int slot){return "w"+wid+"_s"+slot+"_"+System.currentTimeMillis()+"_"+SEQ.incrementAndGet();}
 public static JSONObject process(Context c,JSONObject cmd){synchronized(LOCK){String commandId=cmd.optString("commandId","cmd_"+SEQ.incrementAndGet()),actionId=cmd.optString("actionId"),type=cmd.optString("commandType"),id=cmd.optString("activityId");JSONObject s=state(c);long rev=s.optLong("revision",0L);try{if(actionId.isEmpty()||type.isEmpty())return result(commandId,actionId,INVALID,rev,"Missing actionId or commandType");JSONObject old=recent(s,actionId);if(old!=null)return result(commandId,actionId,DUPLICATE,old.optLong("processedRevision",rev),"Already processed");JSONObject expected=cmd.optJSONObject("expected");if(expected==null)expected=new JSONObject();JSONObject payload=cmd.optJSONObject("payload");if(payload==null)payload=new JSONObject();JSONObject activity=activity(s,id);if(!"CLEAR_HISTORY".equals(type)&&!"IMPORT_STATE".equals(type)&&activity==null)return result(commandId,actionId,NOT_FOUND,rev,"Activity missing");if(activity!=null&&!activity.optBoolean("enabled",true))return result(commandId,actionId,DISABLED,rev,"Activity disabled");JSONObject active=object(s,"active");JSONArray logs=array(s,"logs");String currentMode=activity==null?"":activity.optString("mode","times"),expectedMode=expected.optString("mode",currentMode);if(activity!=null&&!expectedMode.equals(currentMode))return result(commandId,actionId,MODE_MISMATCH,rev,currentMode);String status;
 if("ADD_TIMES".equals(type)){if(!"times".equals(currentMode))return result(commandId,actionId,MODE_MISMATCH,rev,currentMode);JSONObject l=new JSONObject();l.put("id","log_"+(rev+1));l.put("typeId",id);l.put("mode","times");l.put("timestamp",payload.optString("timestamp",utc()));l.put("durationMs",0);l.put("actionId",actionId);logs.put(l);status=APPLIED;}
 else if("START_TIMING".equals(type)){if(!"timing".equals(currentMode))return result(commandId,actionId,MODE_MISMATCH,rev,currentMode);if(active.has(id))return result(commandId,actionId,MISMATCH,rev,"Already running");long received=System.currentTimeMillis(),last=s.optJSONObject("lastTimingActions")==null?0:s.optJSONObject("lastTimingActions").optLong(id,0);if(received-last<TIMING_DEBOUNCE_MS)return result(commandId,actionId,DUPLICATE,rev,"Rapid timing action");active.put(id,payload.optString("startedAt",utc()));JSONObject lastMap=object(s,"lastTimingActions");lastMap.put(id,received);s.put("lastTimingActions",lastMap);status=APPLIED;}
 else if("STOP_TIMING".equals(type)){if(!"timing".equals(currentMode))return result(commandId,actionId,MODE_MISMATCH,rev,currentMode);if(!active.has(id))return result(commandId,actionId,MISMATCH,rev,"Already stopped");String st=active.optString(id),ended=payload.optString("endedAt",utc());long expectedStart=expected.optLong("startedEpoch",parse(st));if(Math.abs(expectedStart-parse(st))>1000)return result(commandId,actionId,SESSION_MISMATCH,rev,"Different timing session");JSONObject l=new JSONObject();l.put("id","log_"+(rev+1));l.put("typeId",id);l.put("mode","timing");l.put("timestamp",st);l.put("startTime",st);l.put("endTime",ended);l.put("durationMs",Math.max(0,parse(ended)-parse(st)));l.put("actionId",actionId);logs.put(l);active.remove(id);status=APPLIED;}
 else if("UPDATE_ACTIVITY".equals(type)){JSONObject changes=payload.optJSONObject("changes");if(changes==null)return result(commandId,actionId,INVALID,rev,"Missing changes");String newMode=changes.optString("mode",currentMode);if("times".equals(newMode)&&active.has(id)){String policy=payload.optString("runningTimingPolicy","DISCARD_AND_STOP");if("REJECT_IF_RUNNING".equals(policy))return result(commandId,actionId,MISMATCH,rev,"Timing running");if("SAVE_AND_STOP".equals(policy)){String st=active.optString(id),ended=utc();JSONObject l=new JSONObject();l.put("id","log_"+(rev+1));l.put("typeId",id);l.put("mode","timing");l.put("timestamp",st);l.put("startTime",st);l.put("endTime",ended);l.put("durationMs",Math.max(0,parse(ended)-parse(st)));logs.put(l);}active.remove(id);}Iterator<String> keys=changes.keys();while(keys.hasNext()){String k=keys.next();activity.put(k,changes.get(k));}status=APPLIED;}
 else if("CLEAR_HISTORY".equals(type)){logs=new JSONArray();active=new JSONObject();status=APPLIED;}
 else if("IMPORT_STATE".equals(type)){JSONObject ns=payload.optJSONObject("state");if(ns==null)return result(commandId,actionId,INVALID,rev,"Missing state");s=ns;logs=array(s,"logs");active=object(s,"active");status=APPLIED;}
 else return result(commandId,actionId,INVALID,rev,"Unknown command");
 rev=rev+1;s.put("revision",rev);s.put("updatedAt",utc());s.put("logs",logs);s.put("active",active);remember(s,actionId,type,status,rev);if(!commit(c,s))return result(commandId,actionId,FAILED,rev-1,"Commit failed");ActivityWidgetProvider.refreshAll(c);return result(commandId,actionId,status,rev,null);}catch(Exception e){return result(commandId,actionId,FAILED,rev,e.getMessage());}}}
}
