package com.nhatkytimestiming.app;
import android.app.*;import android.appwidget.AppWidgetManager;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.widget.*;import org.json.*;import java.util.*;
public class WidgetConfigActivity extends Activity{
 int wid=AppWidgetManager.INVALID_APPWIDGET_ID,cap=10;final ArrayList<String> selected=new ArrayList<>();TextView count;LinearLayout list;
 public void onCreate(Bundle b){super.onCreate(b);setResult(RESULT_CANCELED);wid=getIntent().getIntExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,wid);if(wid==AppWidgetManager.INVALID_APPWIDGET_ID){finish();return;}cap=ActivityWidgetProvider.capacity(this,wid);build();load();}
 TextView tv(String t,int sp){TextView v=new TextView(this);v.setText(t);v.setTextSize(sp);v.setTextColor(Color.rgb(55,24,32));v.setPadding(14,10,14,10);return v;}
 void build(){ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,30);root.setBackgroundColor(Color.rgb(255,248,230));TextView title=tv("Chọn hoạt động cho widget",22);title.setTypeface(null,1);root.addView(title);root.addView(tv(cap==20?"Chế độ 20 ô · 5 × 4":"Chế độ 10 ô · 5 × 2",14));count=tv("0 / "+cap,15);root.addView(count);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);Button save=new Button(this);save.setText("Lưu widget");save.setOnClickListener(v->save());root.addView(save);sc.addView(root);setContentView(sc);}
 void load(){JSONObject s=ActivityWidgetProvider.state(this);JSONArray a=ActivityWidgetProvider.types(s);String old=getSharedPreferences(ActivityWidgetProvider.CONFIG_PREFS,0).getString("selected_"+wid,"[]");try{JSONArray x=new JSONArray(old);for(int i=0;i<x.length()&&i<cap;i++)selected.add(x.optString(i));}catch(Exception ignored){}for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null||!o.optBoolean("enabled",true))continue;String id=o.optString("id"),label=o.optString("icon","•")+"  "+o.optString("name")+"  · "+("timing".equals(o.optString("mode"))?"Timing":"Times");CheckBox cb=new CheckBox(this);cb.setText(label);cb.setTextSize(15);cb.setChecked(selected.contains(id));cb.setOnCheckedChangeListener((b,on)->{if(on){if(selected.size()>=cap){b.setChecked(false);Toast.makeText(this,"Tối đa "+cap+" hoạt động",Toast.LENGTH_SHORT).show();return;}selected.add(id);}else selected.remove(id);refresh();});list.addView(cb);}refresh();}
 void refresh(){count.setText(selected.size()+" / "+cap);}void save(){JSONArray a=new JSONArray();for(String id:selected)a.put(id);getSharedPreferences(ActivityWidgetProvider.CONFIG_PREFS,0).edit().putString("selected_"+wid,a.toString()).commit();ActivityWidgetProvider.update(this,AppWidgetManager.getInstance(this),wid);Intent r=new Intent();r.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,wid);setResult(RESULT_OK,r);finish();}
}
